# .travis.yml
language: go

services:
  - docker

go:
  - "1.12.x"

script:
  - ./.travis.gofmt.sh
  - go vet ./...
  - go test -v -race $(go list ./... | grep -v vendor)
  - export TAG="1.0"
  - export REPO=$DOCKER_USERNAME/produce-demo
  - docker build -t $REPO:$TAG -t $REPO:latest -f Dockerfile .
  - bash ./docker_integ

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
